version: "3.8"

services:
  postgresdb:
    image: postgres
    restart: unless-stopped
    env_file: ./.env
    ports:
      - ${MYSQL_LOCAL_PORT}:${MYSQL_DOCKER_PORT}
    environment:
      MYSQL_USER: ${MYSQL_USER}
      POSTGRES_PASSWORD: ${MYSQL_PASSWORD}
      POSTGRES_DB: ${MYSQL_DATABASE}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 30s
      retries: 3
  app:
    depends_on:
      - postgresdb
    restart: on-failure
    image: posts-service
    build: .
    env_file: ./.env
    ports:
      - ${SPRING_LOCAL_PORT}:${SPRING_DOCKER_PORT}
      - ${DEBUG_PORT}:${DEBUG_PORT}
    environment:
      SPRING_APPLICATION_jSON: '{
      "spring.datasource.url" : "jdbc:mysql://${MYSQL_ENDPOINTS}:${MYSQL_DOCKER_PORT}/${MYSQL_DATABASE}",
      "spring.datasource.username" : "${MYSQL_USER}",
      "spring.datasource.password" : "${MYSQL_PASSWORD}",
      "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQLDialect"}'
      JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:${DEBUG_PORT}"
