SET FOREIGN_KEY_CHECKS = 0;
TRUNCATE TABLE cart_items;
TRUNCATE TABLE shopping_carts;
TRUNCATE TABLE books;
TRUNCATE TABLE users;
TRUNCATE TABLE roles;
TRUNCATE TABLE user_roles;
SET FOREIGN_KEY_CHECKS = 1;
